#!/bin/bash

# Target the plain text colors file generated by pywal
COLORS_FILE="$HOME/.cache/wal/colors" # Change this path if your colors file is stored elsewhere (e.g., ~/.cache/wal/colors)

# Ensure the colors file exists
if [[ ! -f "$COLORS_FILE" ]]; then
    echo "Error: $COLORS_FILE not found!"
    exit 1
fi

# Read the colors file line-by-line into an array (indices 0 to 15)
mapfile -t wal_colors < "$COLORS_FILE"

# Find Firefox default profile
# Added 'head -n 1' to ensure only one profile is targeted if multiple exist
PROFILE_DIR=$(find ~/.config/mozilla/firefox -maxdepth 1 -type d -name "*.default-release" | head -n 1)

if [[ -z "$PROFILE_DIR" ]]; then
    echo "Error: Default Firefox profile not found!"
    exit 1
fi

CHROME_DIR="$PROFILE_DIR/chrome"
mkdir -p "$CHROME_DIR"

# Write userChrome.css with full customization mapped to Pywal variables
cat sample.css > "$CHROME_DIR/userChrome.css" 
