#!/bin/bash

# Target the plain text colors file generated by pywal
COLORS_FILE="$HOME/.cache/wal/colors" # Change this path if your colors file is stored elsewhere (e.g., ~/.cache/wal/colors)

# Ensure the colors file exists
if [[ ! -f "$COLORS_FILE" ]]; then
    echo "Error: $COLORS_FILE not found!"
    exit 1
fi

# Read the colors file line-by-line into an array (indices 0 to 15)
mapfile -t wal_colors < "$COLORS_FILE"

# Find Firefox default profile
# Added 'head -n 1' to ensure only one profile is targeted if multiple exist
PROFILE_DIR=$(find ~/.mozilla/firefox -maxdepth 1 -type d -name "*.default-release" | head -n 1)

if [[ -z "$PROFILE_DIR" ]]; then
    echo "Error: Default Firefox profile not found!"
    exit 1
fi

CHROME_DIR="$PROFILE_DIR/chrome"
mkdir -p "$CHROME_DIR"

# Write userChrome.css with full customization mapped to Pywal variables
cat > "$CHROME_DIR/userChrome.css" <<EOL
:root {
    /* Define the 16-color Pywal palette extracted from your file */
    --color0:  ${wal_colors[0]};
    --color1:  ${wal_colors[1]};
    --color2:  ${wal_colors[2]};
    --color3:  ${wal_colors[3]};
    --color4:  ${wal_colors[4]};
    --color5:  ${wal_colors[5]};
    --color6:  ${wal_colors[6]};
    --color7:  ${wal_colors[7]};
    --color8:  ${wal_colors[8]};
    --color9:  ${wal_colors[9]};
    --color10: ${wal_colors[10]};
    --color11: ${wal_colors[11]};
    --color12: ${wal_colors[12]};
    --color13: ${wal_colors[13]};
    --color14: ${wal_colors[14]};
    --color15: ${wal_colors[15]};

    /* =========================================================
       MAP PYWAL COLORS TO FIREFOX ELEMENTS HERE 
       Change the var(--colorX) to customize your theme!
       ========================================================= */
    
    /* General Toolbar & Navigation */
    --uc-toolbar-bg:      var(--color1);
    --uc-toolbar-fg:      var(--color7);

    /* Tabs */
    --uc-tab-active-bg:   var(--color4);
    --uc-tab-active-fg:   var(--color0);
    --uc-tab-inactive-bg: var(--color1);
    --uc-tab-inactive-fg: var(--color7);
    --uc-tab-hover-bg:    var(--color2);

    /* URL Bar (Awesome Bar) */
    --uc-urlbar-bg:       var(--color8);
    --uc-urlbar-fg:       var(--color7);
    --uc-urlbar-border:   var(--color4);

    /* Context Menus & Popups */
    --uc-popup-bg:        var(--color0);
    --uc-popup-fg:        var(--color7);
    --uc-popup-hover-bg:  var(--color4);
    --uc-popup-hover-fg:  var(--color0);
}

/* --- APPLY VARIABLES TO FIREFOX ELEMENTS --- */

/* General Toolbar Background */
#navigator-toolbox,
#TabsToolbar,
#PersonalToolbar,
#nav-bar {
    background-color: var(--uc-toolbar-bg) !important;
    color: var(--uc-toolbar-fg) !important;
}

/* Tab Backgrounds */
.tabbrowser-tab .tab-background {
    background-color: var(--uc-tab-inactive-bg) !important;
}
.tabbrowser-tab .tab-label {
    color: var(--uc-tab-inactive-fg) !important;
}

/* Hovered Tab */
.tabbrowser-tab:hover .tab-background {
    background-color: var(--uc-tab-hover-bg) !important;
}

/* Active Tab */
.tabbrowser-tab[selected="true"] .tab-background {
    background-color: var(--uc-tab-active-bg) !important;
}
.tabbrowser-tab[selected="true"] .tab-label {
    color: var(--uc-tab-active-fg) !important;
}

/* URL Bar */
#urlbar-background {
    background-color: var(--color1) !important;
    # border: 1px solid var(--uc-urlbar-border) !important;
}
#urlbar-input {
    color: var(--color1) !important;
}

/* Context Menus and Popups */
menupopup, panel {
    --panel-background: var(--uc-popup-bg) !important;
    --panel-color: var(--uc-popup-fg) !important;
}

menuitem:hover, menu:hover {
    background-color: var(--uc-popup-hover-bg) !important;
    color: var(--uc-popup-hover-fg) !important;
}
EOL

echo "userChrome.css updated! You can edit the mappings inside the script to change element colors."
