#!/bin/bash

# Target the plain text colors file generated by pywal
COLORS_FILE="$HOME/.cache/wal/colors" # Change this path if your colors file is stored elsewhere (e.g., ~/.cache/wal/colors)

# Ensure the colors file exists
if [[ ! -f "$COLORS_FILE" ]]; then
    echo "Error: $COLORS_FILE not found!"
    exit 1
fi

# Read the colors file line-by-line into an array (indices 0 to 15)
mapfile -t wal_colors < "$COLORS_FILE"

# Find Firefox default profile
# Added 'head -n 1' to ensure only one profile is targeted if multiple exist
PROFILE_DIR=$(find ~/.mozilla/firefox -maxdepth 1 -type d -name "*.default-release" | head -n 1)

if [[ -z "$PROFILE_DIR" ]]; then
    echo "Error: Default Firefox profile not found!"
    exit 1
fi

CHROME_DIR="$PROFILE_DIR/chrome"
mkdir -p "$CHROME_DIR"

# Write userChrome.css with full customization mapped to Pywal variables
cat > "$CHROME_DIR/userChrome.css" <<EOL
:root {
    /* General Toolbar & Navigation */
    --uc-toolbar-bg:      var(--color1);
    --uc-toolbar-fg:      var(--color7);

    /* Tabs */
    --uc-tab-active-bg:   var(--color4);
    --uc-tab-active-fg:   var(--color0);
    --uc-tab-inactive-bg: var(--color1);
    --uc-tab-inactive-fg: var(--color7);
    --uc-tab-hover-bg:    var(--color2);

    /* URL Bar (Awesome Bar) */
    --uc-urlbar-bg:       var(--color8);
    --uc-urlbar-fg:       var(--color7);
    --uc-urlbar-border:   var(--color4);

    /* Context Menus & Popups */
    --uc-popup-bg:        var(--color0);
    --uc-popup-fg:        var(--color7);
    --uc-popup-hover-bg:  var(--color4);
    --uc-popup-hover-fg:  var(--color0);
}

/* --- APPLY VARIABLES TO FIREFOX ELEMENTS --- */

/* General Toolbar Background */
#navigator-toolbox,
#TabsToolbar,
#PersonalToolbar,
#nav-bar {
    background-color: var(--uc-toolbar-bg) !important;
    color: var(--uc-toolbar-fg) !important;
}

/* Tab Backgrounds */
.tabbrowser-tab .tab-background {
    background-color: var(--uc-tab-inactive-bg) !important;
}
.tabbrowser-tab .tab-label {
    color: var(--uc-tab-inactive-fg) !important;
}

/* Hovered Tab */
.tabbrowser-tab:hover .tab-background {
    background-color: var(--uc-tab-hover-bg) !important;
}

/* Active Tab */
.tabbrowser-tab[selected="true"] .tab-background {
    background-color: var(--uc-tab-active-bg) !important;
}
.tabbrowser-tab[selected="true"] .tab-label {
    color: var(--uc-tab-active-fg) !important;
}

/* URL Bar Base */
#urlbar-background {
    background-color: var(--color1) !important;
    /* border: 1px solid var(--uc-urlbar-border) !important; */
}
#urlbar-input {
    color: var(--color1) !important;
}

/* --- URL BAR DROPDOWN (TRANSPARENT) --- */

/* Makes the background of the expanded URL bar transparent */
#urlbar[open] > #urlbar-background {
    background-color: transparent !important;
    box-shadow: none !important; /* Removes the default dropdown shadow */
}

/* Ensures the suggestion results container is also transparent */
.urlbarView {
    background-color: transparent !important;
}

/* Optional: Add a slight hover effect to suggested items so you can see what you are selecting */
.urlbarView-row:hover > .urlbarView-row-inner {
    background-color: #909 !important;
    # color: var(--color0) !important;
}
/* Context Menus and Popups */
menupopup, panel {
    --panel-background: var(--uc-popup-bg) !important;
    --panel-color: var(--uc-popup-fg) !important;
}

menuitem:hover, menu:hover {
    background-color: var(--uc-popup-hover-bg) !important;
    color: var(--uc-popup-hover-fg) !important;
}

/* --- AUTO-HIDE ENTIRE TOP BAR --- */
#navigator-toolbox {
    position: absolute !important;
    display: block !important;
    width: 100vw !important;
    z-index: 100 !important;
    /* Move the bar off-screen, leaving a 4px invisible hit-area to catch your mouse */
    transform: translateY(calc(-100% + 20px)) !important;
    opacity: 0 !important;
    transition: transform 0.25s ease-in-out, opacity 0.25s ease-in-out !important;
}

/* Reveal top bar on hover or when clicking inside (e.g., using Ctrl+L to type a URL) */
#navigator-toolbox:hover,
#navigator-toolbox:focus-within {
    transform: translateY(0) !important;
    opacity: 1 !important;
}

/* Auto-hide the nav bar, reveal on hover */
#nav-bar {
  min-height: 0 !important;
  max-height: 0 !important;
  visibility: hidden !important;
  transition: all 0.2s ease-in-out !important;
  opacity: 0 !important;
}

#navigator-toolbox:hover #nav-bar,
#navigator-toolbox:focus-within #nav-bar {
  max-height: 40px !important; /* Adjust based on your UI density */
  visibility: visible !important;
  opacity: 1 !important;
}
/* Make the expanded URL bar and dropdown background semi-transparent */
/* #urlbar[breakout][breakout-extend] > #urlbar-background {
    background-color: rgba(25, 25, 25, 0.65) !important; /* Dark theme semi-transparent */
    /* Use rgba(255, 255, 255, 0.65) if you use a Light theme */
    
    backdrop-filter: blur(8px) !important; /* Optional: gives a frosted glass effect */
}
EOL

echo "userChrome.css updated! You can edit the mappings inside the script to change element colors."
