/* generated by org-sync.py — do not edit */
window.ORG = {
  "generated": "2026-08-03T13:20:37.923944-04:00",
  "today": "2026-08-03",
  "horizonDays": 14,
  "categories": [
    "school"
  ],
  "items": [
    {
      "title": "Something",
      "keyword": "TODO",
      "priority": null,
      "tags": [
        "main",
        "thingy"
      ],
      "category": "school",
      "color": 0,
      "crumb": "",
      "deadline": "2025-08-02",
      "date": "2025-08-02",
      "kind": "deadline",
      "repeat": false
    },
    {
      "title": "Thingy",
      "keyword": "TODO",
      "priority": null,
      "tags": [
        "aieaciea",
        "main"
      ],
      "category": "school",
      "color": 0,
      "crumb": "",
      "deadline": "2025-08-03",
      "date": "2025-08-03",
      "kind": "deadline",
      "repeat": false
    },
    {
      "title": "Follow Up",
      "keyword": "TODO",
      "priority": null,
      "tags": [
        "main",
        "test"
      ],
      "category": "school",
      "color": 0,
      "crumb": "",
      "deadline": "2026-07-30",
      "date": "2026-07-30",
      "kind": "deadline",
      "repeat": false
    }
  ],
  "counts": {
    "dated": 3,
    "backlog": 0
  }
};
