/* generated by org-sync.py — do not edit */
window.ORG = {
  "generated": "2026-08-08T16:01:07.317629-04:00",
  "today": "2026-08-08",
  "horizonDays": 21,
  "categories": [
    "school",
    "work"
  ],
  "items": [
    {
      "title": "MATH-000 Combinatorics",
      "keyword": "TODO",
      "priority": null,
      "tags": [],
      "category": "school",
      "color": 1,
      "crumb": "",
      "railColor": "#df8e1d",
      "date": "2026-08-10",
      "kind": "timestamp",
      "repeat": true,
      "time": "07:00",
      "endTime": "08:00"
    },
    {
      "title": "MATH-000 Optimization",
      "keyword": "TODO",
      "priority": null,
      "tags": [],
      "category": "school",
      "color": 1,
      "crumb": "",
      "railColor": "#df8e1d",
      "date": "2026-08-11",
      "kind": "timestamp",
      "repeat": true,
      "time": "07:00",
      "endTime": "08:00"
    },
    {
      "title": "MATH-000 Real Analysis",
      "keyword": "TODO",
      "priority": null,
      "tags": [],
      "category": "school",
      "color": 1,
      "crumb": "",
      "railColor": "#df8e1d",
      "date": "2026-08-11",
      "kind": "timestamp",
      "repeat": true,
      "time": "08:00",
      "endTime": "09:00"
    },
    {
      "title": "CMSC Tutoring",
      "keyword": "TODO",
      "priority": null,
      "tags": [
        "work"
      ],
      "category": "work",
      "color": 2,
      "crumb": "",
      "railColor": "#ea76cb",
      "date": "2026-08-11",
      "kind": "timestamp",
      "repeat": true,
      "time": "12:00",
      "endTime": "13:00"
    },
    {
      "title": "MATH-000 Combinatorics",
      "keyword": "TODO",
      "priority": null,
      "tags": [],
      "category": "school",
      "color": 1,
      "crumb": "",
      "railColor": "#df8e1d",
      "date": "2026-08-12",
      "kind": "timestamp",
      "repeat": true,
      "time": "07:00",
      "endTime": "08:00"
    },
    {
      "title": "MATH-000 Optimization",
      "keyword": "TODO",
      "priority": null,
      "tags": [],
      "category": "school",
      "color": 1,
      "crumb": "",
      "railColor": "#df8e1d",
      "date": "2026-08-13",
      "kind": "timestamp",
      "repeat": true,
      "time": "07:00",
      "endTime": "08:00"
    },
    {
      "title": "MATH-000 Real Analysis",
      "keyword": "TODO",
      "priority": null,
      "tags": [],
      "category": "school",
      "color": 1,
      "crumb": "",
      "railColor": "#df8e1d",
      "date": "2026-08-13",
      "kind": "timestamp",
      "repeat": true,
      "time": "08:00",
      "endTime": "09:00"
    },
    {
      "title": "MATH-000 Seminar",
      "keyword": "TODO",
      "priority": null,
      "tags": [],
      "category": "school",
      "color": 1,
      "crumb": "",
      "railColor": "#df8e1d",
      "date": "2026-08-14",
      "kind": "timestamp",
      "repeat": true,
      "time": "07:00",
      "endTime": "08:00"
    }
  ],
  "counts": {
    "dated": 8,
    "backlog": 0
  }
};
