/* generated by org-sync.py — do not edit */
window.ORG = {
  "generated": "2026-08-20T15:23:09.933699-04:00",
  "today": "2026-08-20",
  "horizonDays": 21,
  "categories": [
    "buffer",
    "commute",
    "main",
    "school"
  ],
  "items": [
    {
      "title": "MATH 302: Introduction to Mathematical Analysis II",
      "keyword": null,
      "priority": null,
      "tags": [],
      "category": "school",
      "color": 1,
      "crumb": "",
      "railColor": "#df8e1d",
      "date": "2026-08-24",
      "kind": "timestamp",
      "repeat": true,
      "time": "13:00",
      "endTime": "14:15"
    },
    {
      "title": "Drive",
      "keyword": null,
      "priority": null,
      "tags": [
        "main"
      ],
      "category": "commute",
      "color": 4,
      "crumb": "",
      "date": "2026-08-25",
      "kind": "timestamp",
      "repeat": false,
      "time": "07:45",
      "endTime": "08:15"
    },
    {
      "title": "Buffer",
      "keyword": null,
      "priority": null,
      "tags": [
        "main"
      ],
      "category": "buffer",
      "color": 3,
      "crumb": "",
      "railColor": "#939393",
      "date": "2026-08-25",
      "kind": "timestamp",
      "repeat": false,
      "time": "08:15",
      "endTime": "08:30"
    },
    {
      "title": "MATH 475: Combinatorics and Graph Theory",
      "keyword": null,
      "priority": null,
      "tags": [],
      "category": "school",
      "color": 1,
      "crumb": "",
      "railColor": "#df8e1d",
      "date": "2026-08-25",
      "kind": "timestamp",
      "repeat": true,
      "time": "08:30",
      "endTime": "09:45"
    },
    {
      "title": "MATH 380: Introduction to Optimization for Data Science",
      "keyword": null,
      "priority": null,
      "tags": [],
      "category": "school",
      "color": 1,
      "crumb": "",
      "railColor": "#df8e1d",
      "date": "2026-08-25",
      "kind": "timestamp",
      "repeat": true,
      "time": "13:00",
      "endTime": "14:15"
    },
    {
      "title": "MATH 385: Introduction to Mathematical Modeling",
      "keyword": null,
      "priority": null,
      "tags": [],
      "category": "school",
      "color": 1,
      "crumb": "",
      "railColor": "#df8e1d",
      "date": "2026-08-25",
      "kind": "timestamp",
      "repeat": true,
      "time": "14:30",
      "endTime": "15:45"
    },
    {
      "title": "MATH 302: Introduction to Mathematical Analysis II",
      "keyword": null,
      "priority": null,
      "tags": [],
      "category": "school",
      "color": 1,
      "crumb": "",
      "railColor": "#df8e1d",
      "date": "2026-08-26",
      "kind": "timestamp",
      "repeat": true,
      "time": "13:00",
      "endTime": "14:15"
    },
    {
      "title": "MATH 475: Combinatorics and Graph Theory",
      "keyword": null,
      "priority": null,
      "tags": [],
      "category": "school",
      "color": 1,
      "crumb": "",
      "railColor": "#df8e1d",
      "date": "2026-08-27",
      "kind": "timestamp",
      "repeat": true,
      "time": "08:30",
      "endTime": "09:45"
    },
    {
      "title": "MATH 380: Introduction to Optimization for Data Science",
      "keyword": null,
      "priority": null,
      "tags": [],
      "category": "school",
      "color": 1,
      "crumb": "",
      "railColor": "#df8e1d",
      "date": "2026-08-27",
      "kind": "timestamp",
      "repeat": true,
      "time": "13:00",
      "endTime": "14:15"
    },
    {
      "title": "MATH 385: Introduction to Mathematical Modeling",
      "keyword": null,
      "priority": null,
      "tags": [],
      "category": "school",
      "color": 1,
      "crumb": "",
      "railColor": "#df8e1d",
      "date": "2026-08-27",
      "kind": "timestamp",
      "repeat": true,
      "time": "14:30",
      "endTime": "15:45"
    },
    {
      "title": "MATH 479: Seminar",
      "keyword": null,
      "priority": null,
      "tags": [],
      "category": "school",
      "color": 1,
      "crumb": "",
      "railColor": "#df8e1d",
      "date": "2026-08-28",
      "kind": "timestamp",
      "repeat": true,
      "time": "14:00",
      "endTime": "15:00"
    },
    {
      "title": "Message Micah/Beck Course Catalog",
      "keyword": "TODO",
      "priority": null,
      "tags": [
        "main"
      ],
      "category": "main",
      "color": 0,
      "crumb": "",
      "railColor": "#7287fd"
    },
    {
      "title": "Message Tejas Time Conflict",
      "keyword": "TODO",
      "priority": null,
      "tags": [
        "main"
      ],
      "category": "main",
      "color": 0,
      "crumb": "",
      "railColor": "#7287fd"
    }
  ],
  "counts": {
    "dated": 11,
    "backlog": 2
  }
};
