- name: Clone yay
  git:
    repo: https://aur.archlinux.org/yay.git
    dest: /tmp/yay

- name: Build and install yay
  command:
    chdir: "/tmp/yay"
    cmd: "makepkg -sfi --noconfirm"
    creates: /usr/bin/yay

