- hosts: localhost
  tasks:
    - name: Make sure we have a 'wheel' group
      ansible.builtin.group:
        name: wheel
        state: present

    - name: Allow 'wheel' group to have passwordless sudo
      ansible.builtin.lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Add sudoers users to wheel group
      ansible.builtin.user:
        name: ansible
        groups: wheel
        append: yes
        state: present
        createhome: yes

    - name: Update pacman
      become: true
      ansible.builtin.pacman:
        update_cache: true
      tags: 
        - install

    - name: Install dependencies for yay
      become: true
      ansible.builtin.pacman:
        name:
          - base-devel
          - git
      tags: 
        - install

    - include_tasks: tasks/yay.yml
    - include_tasks: tasks/core.yml
    - include_tasks: tasks/hypr.yml
    - include_tasks: tasks/zsh.yml
    - include_tasks: tasks/nvim.yml

