- hosts: localhost
  pre_tasks:
    - name: Update pacman
      become: true
      pacman:
        update_cache: true
      tags: install

    - name: Install dependencies for yay
      become: true
      pacman:
        name:
          - base-devel
          - git
      tags: install

  tasks:
    - include_tasks: tasks/yay.yml
    - include_tasks: tasks/core.yml
    - include_tasks: tasks/zsh.yml
    - include_tasks: tasks/nvim.yml
    - include_tasks: tasks/hypr.yml

